In [2]:
import numpy as np
x = np.arange(50)
print(x)

Array from 0 to 50:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [18]:
a=np.ones(10)
b=np.zeros(10)
c=np.array([6,6,6,6,6,6,6,6,6,6])
np.concatenate([a,b,c])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.])

In [26]:
x = np.arange(20, 32)
a= np. reshape(x,(3,4),'C')
print(a)

[[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [30]:
a= np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
a= np.diag([1,2,3,4,5])
print(a)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [51]:
a=np.array([[1,2,3,4,5],
           [5,6,7,8,9]])
print(np.nansum(a))
print(a.sum(axis=0))
print(a.sum(axis=1))

50
[ 6  8 10 12 14]
[15 35]


In [ ]:
#Seasons
Seasons = ["2011","2012","2013","2014","2015","2016","2017","2018","2019","2020","2021"]
Sdict = {"2011":0,"2012":1,"2013":2,"2014":3,"2015":4,"2016":5,"2017":6,"2018":7,"2019":8,"2020":9,"2021":10}

#Players
Players = ["FernandoTorres","WayneRooney","DarrenBent","JohnTerry","MikelArteta","JoeHart","CharlesNZogbial","BranislavIvanovic","DavidDeGea","RomeluLukaku"]
Pdict = {"FernandoTorres":0,"WayneRooney":1,"DarrenBen":2,"JohnTerry":3,"MikelArteta":4,"JoeHart":5,"CharlesNZogbial":6,"BranislavIvanovic":7,"DavidDeGea":8,"RomeluLukaku":9}

#Salaries
FernandoTorre_Salary = [16938935,]
WayneRooney_Salary = [9360000,]
DarrenBen_Salary = [6826000,]
JohnTerry_Salary = [7020000]
MikelArteta_Salary = [6540000]
JoeHart_Salary = [4160000]
CharlesNZogbial_Salary = [3980000]
BranislavIvanovic_Salary = [3900000]
DavidDeGea_Salary = [3900000]
RomeluLukaku_Salary = [4084305]
#Matrix
Salary = np.array([FernandoTorre_Salary, WayneRooney_Salary, DarrenBen_Salary, JohnTerry_Salary, MikelArteta_Salary, JoeHart_Salary, CharlesNZogbial_Salary, BranislavIvanovic_Salary, DavidDeGea_Salary, RomeluLukaku_Salary])

#Games
FernandoTorre_G = [340362,]
WayneRooney_G = [180000,]
DarrenBen_G = [137769,]
JohnTerry_G = []
MikelArteta_G = []
JoeHart_G = []
CharlesNZogbial_G = []
BranislavIvanovic_G = []
DavidDeGea_G = []
RomeluLukaku_G = []
#Matrix
Games = np.array([FernandoTorre_G, WayneRooney_G, DarrenBen_G, JohnTerry_G, MikelArteta_G, JoeHart_G, CharlesNZogbial_G, BranislavIvanovic_G, DavidDeGea_G, RomeluLukaku_G])

#Points
WayneRooney_PTS = []
DarrenBen_PTS = []
JohnTerry_PTS = []
MikelArteta_PTS = []
JoeHart_PTS = []
CharlesNZogbial_PTS = []
BranislavIvanovic_PTS = []
DavidDeGea_PTS = []
RomeluLukaku_PTS = []
#Matrix
Points = np.array([FernandoTorre_PTS, WayneRooney_PTS, DarrenBen_PTS, JohnTerry_PTS, MikelArteta_PTS, JoeHart_PTS, CharlesNZogbial_PTS, BranislavIvanovic_PTS, DavidDeGea_PTS, RomeluLukaku_PTS])